/*
 * This file is part of INAV.
 *
 * INAV is free software. You can redistribute this software
 * and/or modify this software under the terms of the
 * GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option)
 * any later version.
 *
 * INAV is distributed in the hope that it
 * will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this software.
 *
 * If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * ExpressLRS SPI receiver protocol tests, compiled once per OTA version
 * (rx_expresslrs_v3_unittest.cc / rx_expresslrs_v4_unittest.cc).
 *
 * Expected values come from rx_expresslrs_vectors_v{3,4}.h, generated by an
 * independent transmitter-side implementation written from upstream
 * ExpressLRS (see rx_expresslrs_vectors_gen.py), except the CRC14 table which
 * is Betaflight's published test vector.
 */

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>

extern "C" {
    #include "platform.h"

    #include "build/debug.h"

    #include "drivers/io.h"
    #include "drivers/rx/expresslrs_driver.h"
    #include "drivers/rx/rx_spi.h"

    #include "fc/fc_init.h"
    #include "fc/runtime_config.h"

    #include "rx/rx.h"
    #include "rx/expresslrs.h"
    #include "rx/expresslrs_common.h"
    #include "rx/expresslrs_impl.h"

    extern uint8_t fhssSequence[ELRS_NR_SEQUENCE_ENTRIES];
    extern uint16_t seqCount;
    extern uint16_t crc14tab[ELRS_CRC_LEN];
    extern elrsReceiver_t receiver;

    static rxRuntimeConfig_t runtimeConfig;
    static rxLinkQualityTracker_e lqTracker;
    static rxConfig_t rxConfigForTest;

    // Stub state
    static bool timerRunning;
    static int timerResumeCount;
    static int saveCount;
}

#include "unittest_macros.h"
#include "gtest/gtest.h"

#if defined(USE_ELRSV3)
#include "rx_expresslrs_vectors_v3.h"
#else
#include "rx_expresslrs_vectors_v4.h"
#endif

static void initReceiverForTest(const char *bindPhrase)
{
    memset(&receiver, 0, sizeof(receiver));
    memset(&runtimeConfig, 0, sizeof(runtimeConfig));
    runtimeConfig.lqTracker = &lqTracker;

    memset(rxExpressLrsSpiConfigMutable(), 0, sizeof(rxExpressLrsSpiConfig_t));
    strncpy(rxExpressLrsSpiConfigMutable()->bindPhrase, bindPhrase, EXPRESSLRS_BIND_PHRASE_MAX_LENGTH);
    rxExpressLrsSpiConfigMutable()->domain = ISM2400;
    rxExpressLrsSpiConfigMutable()->rateIndex = 3; // 250Hz
    rxExpressLrsSpiConfigMutable()->modelId = 0xFF;

    timerRunning = false;
    timerResumeCount = 0;
    saveCount = 0;
    DISABLE_ARMING_FLAG(ARMED);

    ASSERT_TRUE(expressLrsSpiInit(&rxConfigForTest, &runtimeConfig));
}

static rx_spi_received_e feedPacket(const uint8_t *packet, uint8_t *payload)
{
    memcpy((uint8_t *)expressLrsGetRxBuffer(), packet, ELRS_RX_TX_BUFF_SIZE);
    return processRFPacket(payload, 0);
}

TEST(RxExpressLrsUnitTest, Crc14Table)
{
    static const uint16_t expectedCrc14Tab[ELRS_CRC_LEN] = {
        0,28247,62201,40110,52133,42482,14684,22283,
        38730,63773,26035,3044,23791,12984,44566,49217,
        11924,16579,56429,45626,58673,35686,6088,31135,
        47582,55177,19239,9584,29307,7212,32898,61141,
        29567,7464,33158,61393,47322,54925,18979,9332,
        58421,35426,5836,30875,12176,16839,56681,45886,
        24043,13244,44818,49477,38478,63513,25783,2784,
        51873,42230,14424,22031,260,28499,62461,40362,
        51369,42750,14928,21511,780,27995,61941,40866,
        24547,12724,44314,49997,37958,64017,26303,2280,
        58941,34922,5316,31379,11672,17359,57185,45366,
        29047,7968,33678,60889,47826,54405,18475,9852,
        48086,54657,18735,10104,28787,7716,33418,60637,
        11420,17099,56933,45106,59193,35182,5568,31639,
        38210,64277,26555,2540,24295,12464,44062,49737,
        520,27743,61681,40614,51629,43002,15188,21763,
        37202,65285,25515,3580,23287,13472,43022,50777,
        1560,26703,62689,39606,52669,41962,16196,20755,
        49094,53649,19775,9064,29795,6708,34458,59597,
        10380,18139,55925,46114,58153,36222,4560,32647,
        57901,35962,4308,32387,10632,18399,56177,46374,
        30055,6960,34718,59849,48834,53397,19515,8812,
        52409,41710,15936,20503,1820,26955,62949,39858,
        23539,13732,43274,51037,36950,65025,25263,3320,
        23035,14252,43778,50517,37470,64521,24743,3824,
        52913,41190,15432,21023,1300,27459,63469,39354,
        30575,6456,34198,60353,48330,53917,20019,8292,
        57381,36466,4828,31883,11136,17879,55673,46894,
        10884,17619,55421,46634,57633,36726,5080,32143,
        48590,54169,20279,8544,30315,6204,33938,60101,
        1040,27207,63209,39102,53173,41442,15692,21275,
        37722,64781,24995,4084,22783,13992,43526,50257
    };

    generateCrc14Table();
    for (int i = 0; i < ELRS_CRC_LEN; i++) {
        EXPECT_EQ(expectedCrc14Tab[i], crc14tab[i]);
    }
}

TEST(RxExpressLrsUnitTest, FhssSequenceMatchesUpstream)
{
    fhssGenSequence(elrsUidToSeed(elrsTestFhssUid), ISM2400);

    EXPECT_EQ(ELRS_TEST_FHSS_COUNT, seqCount);
    for (int i = 0; i < ELRS_TEST_FHSS_COUNT; i++) {
        EXPECT_EQ(elrsTestFhssSequence[i], fhssSequence[i]) << "index " << i;
    }
}

TEST(RxExpressLrsUnitTest, BindPhraseToUid)
{
    uint8_t uid[6];
    elrsUidFromBindPhrase(ELRS_TEST_BIND_PHRASE, uid);
    for (int i = 0; i < 6; i++) {
        EXPECT_EQ(elrsTestUid[i], uid[i]);
    }
}

TEST(RxExpressLrsUnitTest, InitUsesBindPhrase)
{
    initReceiverForTest(ELRS_TEST_BIND_PHRASE);

    EXPECT_FALSE(receiver.inBindingMode);
    for (int i = 0; i < 6; i++) {
        EXPECT_EQ(elrsTestUid[i], receiver.UID[i]);
    }
    EXPECT_EQ(ELRS_MAX_CHANNELS, runtimeConfig.channelCount);
    EXPECT_EQ(airRateConfig[0][3].index, receiver.modParams->index);
}

TEST(RxExpressLrsUnitTest, InitWithoutUidEntersBindMode)
{
    initReceiverForTest("");

    EXPECT_TRUE(receiver.inBindingMode);
    static const uint8_t bindUID[6] = {0, 1, 2, 3, 4, 5};
    for (int i = 0; i < 6; i++) {
        EXPECT_EQ(bindUID[i], receiver.UID[i]);
    }
}

TEST(RxExpressLrsUnitTest, SyncPacketIsLinkNotRcData)
{
    initReceiverForTest(ELRS_TEST_BIND_PHRASE);
    uint8_t payload[ELRS_RX_TX_BUFF_SIZE] = {0};

    const elrsTestRcVector_t *v = &elrsTestRcVectors[0];
    EXPECT_EQ(RX_SPI_RECEIVED_LINK, feedPacket(v->sync, payload));

    EXPECT_EQ(ELRS_TENTATIVE, receiver.connectionState);
    EXPECT_EQ(ELRS_TEST_SYNC_NONCE, receiver.nonceRX);
    EXPECT_EQ(ELRS_TEST_SYNC_FHSS_INDEX, fhssGetCurrIndex());
    EXPECT_EQ(v->switchMode, receiver.switchMode);
    EXPECT_EQ(1, timerResumeCount);
}

TEST(RxExpressLrsUnitTest, RcPacketIgnoredUntilConnected)
{
    initReceiverForTest(ELRS_TEST_BIND_PHRASE);
    uint8_t payload[ELRS_RX_TX_BUFF_SIZE] = {0};

    const elrsTestRcVector_t *v = &elrsTestRcVectors[0];
    ASSERT_EQ(RX_SPI_RECEIVED_LINK, feedPacket(v->sync, payload));
    ASSERT_EQ(ELRS_TENTATIVE, receiver.connectionState);

    receiver.nonceRX = v->nonce;
    // Valid CRC, but not connected: must never be reported as RC data
    EXPECT_EQ(RX_SPI_RECEIVED_LINK, feedPacket(v->packet, payload));
}

TEST(RxExpressLrsUnitTest, CorruptPacketRejected)
{
    initReceiverForTest(ELRS_TEST_BIND_PHRASE);
    uint8_t payload[ELRS_RX_TX_BUFF_SIZE] = {0};

    uint8_t sync[8];
    memcpy(sync, elrsTestRcVectors[0].sync, sizeof(sync));
    sync[3] ^= 0x10;
    EXPECT_EQ(RX_SPI_RECEIVED_NONE, feedPacket(sync, payload));
    EXPECT_EQ(ELRS_DISCONNECTED, receiver.connectionState);
}

TEST(RxExpressLrsUnitTest, WrongBindPhraseRejected)
{
    initReceiverForTest("some other phrase");
    uint8_t payload[ELRS_RX_TX_BUFF_SIZE] = {0};

    EXPECT_EQ(RX_SPI_RECEIVED_NONE, feedPacket(elrsTestRcVectors[0].sync, payload));
    EXPECT_EQ(ELRS_DISCONNECTED, receiver.connectionState);
}

TEST(RxExpressLrsUnitTest, RcChannelsDecodeLikeUpstream)
{
    const int count = sizeof(elrsTestRcVectors) / sizeof(elrsTestRcVectors[0]);
    int checkedChannels = 0;

    for (int n = 0; n < count; n++) {
        const elrsTestRcVector_t *v = &elrsTestRcVectors[n];
        uint8_t payload[ELRS_RX_TX_BUFF_SIZE] = {0};
        uint16_t rcData[MAX_SUPPORTED_RC_CHANNEL_COUNT] = {0};

        initReceiverForTest(ELRS_TEST_BIND_PHRASE);
        ASSERT_EQ(RX_SPI_RECEIVED_LINK, feedPacket(v->sync, payload)) << "vector " << n;

        // Skip the phase lock handshake: this test covers the packet format
        receiver.connectionState = ELRS_CONNECTED;
        receiver.nonceRX = v->nonce;

        ASSERT_EQ(RX_SPI_RECEIVED_DATA, feedPacket(v->packet, payload)) << "vector " << n;

        expressLrsSetRcDataFromPayload(rcData, payload);
        for (int ch = 0; ch < 16; ch++) {
            if (v->expectedUs[ch]) {
                EXPECT_NEAR(v->expectedUs[ch], rcData[ch], 3) << "vector " << n << " channel " << ch;
                checkedChannels++;
            }
        }
    }

    // Every vector carries 4 sticks + AUX1, most also one round-robin switch
    EXPECT_GT(checkedChannels, count * 5);
}

TEST(RxExpressLrsUnitTest, ModelMatchMismatchNeverDeliversRc)
{
    initReceiverForTest(ELRS_TEST_BIND_PHRASE);
    rxExpressLrsSpiConfigMutable()->modelId = 7; // TX sends model match off
    uint8_t payload[ELRS_RX_TX_BUFF_SIZE] = {0};

    const elrsTestRcVector_t *v = &elrsTestRcVectors[0];
    ASSERT_EQ(RX_SPI_RECEIVED_LINK, feedPacket(v->sync, payload));
    receiver.connectionState = ELRS_CONNECTED;
    receiver.nonceRX = v->nonce;

    EXPECT_EQ(RX_SPI_RECEIVED_LINK, feedPacket(v->packet, payload));
}

TEST(RxExpressLrsUnitTest, LqCalc)
{
    lqReset();
    for (int i = 1; i <= 100; i++) {
        lqNewPeriod();
        lqIncrease();
        EXPECT_EQ(i, lqGet());
    }
    lqNewPeriod();
    lqIncrease();
    EXPECT_EQ(100, lqGet());
    for (int i = 99; i >= 0; i--) {
        lqNewPeriod();
        EXPECT_EQ(i, lqGet());
    }
}

TEST(RxExpressLrsUnitTest, SwitchDecode)
{
    EXPECT_EQ(1000, convertSwitch1b(0));
    EXPECT_EQ(2000, convertSwitch1b(1));
    EXPECT_EQ(1000, convertSwitch3b(0));
    EXPECT_EQ(1275, convertSwitch3b(1));
    EXPECT_EQ(2000, convertSwitch3b(5));
    EXPECT_EQ(1500, convertSwitch3b(7));
    EXPECT_EQ(1000, convertSwitchNb(0, 15));
    EXPECT_EQ(2000, convertSwitchNb(15, 15));
    EXPECT_EQ(1500, convertSwitchNb(16, 15));
}

// STUBS

extern "C" {
    uint8_t systemState = SYSTEM_STATE_READY;
    uint32_t armingFlags;
    int32_t debug[DEBUG32_VALUE_COUNT];
    uint8_t debugMode;
    rxLinkStatistics_t rxLinkStatistics;

    timeUs_t micros(void) { return 0; }
    uint32_t millis(void) { return 0; }

    IO_t IOGetByTag(ioTag_t) { return (IO_t)1; }

    void saveConfigAndNotify(void) { saveCount++; }
    void lqTrackerSet(rxLinkQualityTracker_e *, uint16_t) {}

    bool rxSpiDeviceInit(void) { return true; }
    bool rxSpiExtiConfigured(void) { return true; }
    void rxSpiExtiInit(rxSpiExtiHandlerFn *) {}
    void rxSpiLedBlinkRxLoss(bool) {}
    void rxSpiLedBlinkBind(void) {}
    bool rxSpiCheckBindRequested(bool) { return false; }

    bool sx1280Init(IO_t, IO_t) { return true; }
    void sx1280Config(const uint8_t, const uint8_t, const uint8_t, const uint32_t, const uint8_t, const bool,
        const uint32_t, const uint16_t, const bool) {}
    void sx1280StartReceiving(void) {}
    void sx1280ISR(void) {}
    void sx1280HandleFromTock(void) {}
    bool sx1280HandleFromTick(void) { return false; }
    void sx1280GetLastPacketStats(int8_t *rssi, int8_t *snr) { *rssi = -60; *snr = 20; }
    void sx1280AdjustFrequency(int32_t *, const uint32_t) {}
    void sx1280SetOutputPower(const int8_t) {}

    bool expressLrsInitialiseTimer(void *) { return true; }
    void expressLrsTimerEnableIRQs(void) {}
    void expressLrsUpdateTimerInterval(uint16_t) {}
    void expressLrsUpdatePhaseShift(int32_t) {}
    void expressLrsTimerIncreaseFrequencyOffset(void) {}
    void expressLrsTimerDecreaseFrequencyOffset(void) {}
    void expressLrsTimerResetFrequencyOffset(void) {}
    void expressLrsTimerStop(void) { timerRunning = false; }
    void expressLrsTimerResume(void) { timerRunning = true; timerResumeCount++; }
    bool expressLrsTimerIsRunning(void) { return timerRunning; }
    void expressLrsTimerDebug(void) {}

    void initTelemetry(void) {}
    bool getNextTelemetryPayload(uint8_t *, uint8_t **) { return false; }
    void setTelemetryDataToTransmit(const uint8_t, uint8_t *) {}
    bool isTelemetrySenderActive(void) { return false; }
    uint8_t getCurrentTelemetryPayload(uint8_t *, uint8_t) { return 0; }
    void confirmCurrentTelemetryPayload(const bool) {}
    void updateTelemetryRate(const uint16_t, const uint8_t, const uint8_t) {}

    int constrain(int amt, int low, int high) { return amt < low ? low : (amt > high ? high : amt); }

    int scaleRange(int x, int srcFrom, int srcTo, int destFrom, int destTo) {
        long int a = ((long int) destTo - (long int) destFrom) * ((long int) x - (long int) srcFrom);
        long int b = (long int) srcTo - (long int) srcFrom;
        return (a / b) + destFrom;
    }
}
